### ISSUE TITLE
Add a open source game engine collection

### ISSUE THREAD

**Issue by luzizhuo** [notpresident35/awesome-learn-gamedev#2]
Here is [a collection of open source game engines](https://ossinsight.io/collections/game-engine). I think it's useful for learning game dev.
You can see the overview of open source game engine and which engines are becoming popular, which can be used as a reference for technology selection.

**Comment by dawdle-deer** [comment]
This looks awesome, though I feel this might be better suited for this repo: https://github.com/Calinou/awesome-gamedev

Or, better yet:
https://github.com/leereilly/games#readme

Tools and assets are cool, but only included out of necessity for completion. This list aims to offer general knowledge above all else, and specific tools are included when teaching the general stuff necessitates it. Assets are included to allow people to do work that relies on other roles without having to fill those roles (for example, 3D assets and music are included to support programmers/designers, and rigs are included to support animators). Resources to learn those open-source engines would be a better fit here than a list of the tools themselves.

I will revise some things to make that distinction clearer.

**Comment by luzizhuo** [comment]
Got it. Thank you for the explanation.
