### ISSUE TITLE
How about a section on game engines/frameworks

### ISSUE THREAD

**Issue by sellisd** [notpresident35/awesome-learn-gamedev#6]
As a newcomer into gamedev I found very helpful the list of game engines by language compiled by the github/itch.io game off (e.g.  [Help - I've never created a game before!](https://itch.io/jam/game-off-2022))

**Comment by dawdle-deer** [comment]
Except in rare cases, I am uncomfortable sending new developers off with engines other than Unity and Unreal (and potentially Godot), as these are the engines that recruiters look for, and the only third-party engines that studios typically use. Switching game engines is a major interruption in the learning process, so it is best to start with tools that stay useful in the long term. Additionally, this list avoids lists of tools where possible, as described in the About section. Glad that this helped you, but will not include. 

However, this does highlight another real issue, which is that this list does not clearly explain what a game engine is or why it is useful, and does not explain that Unity and Unreal are game engines. Will include a resource [such as this](https://www.perforce.com/resources/vcs/game-engine-overview) and revise item descriptions to explain this clearly.

**Comment by dawdle-deer** [comment]
Added [How Game Engines Work](https://interestingengineering.com/innovation/how-game-engines-work), revised engine course descriptions appropriately.
