### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [notpresident35/awesome-learn-gamedev#7]
Hello, I found some broken hyperlinks:
- [ ] https://www.gamesparks.com/the-ultimate-list-of-free-and-low-cost-developer-tools-and-resources/ (file: README.md, error: ENOTFOUND)
- [x] http://sigbovik.org (file: README.md, error: EAI_AGAIN)
- [ ] https://docs.google.com/document/d/1DLccwkSK1B8fJ3TV4X1-8ktiDmzgnelkNMamZfz3hYE/edit (file: README.md, status code: 410)
- [ ] https://www.sunyoungkim.org/class/old/hci_f18/pdf/The-Design-of-Everyday-Things-Revised-and-Expanded-Edition.pdf (file: README.md, status code: 404)
- [ ] https://www.gameindustrycareerguide.com/how-to-become-a-video-game-producer/ (file: README.md, status code: 404)
- [ ] https://docs.google.com/document/d/14jsiaFOXuBi9QsXOF2DJVFXCRP4RwqGY3xmMHlqf3y4/edit (file: README.md, status code: 410)

**Comment by dawdle-deer** [comment]
addressed, thank you!
